### ISSUE TITLE
FATAL sqd:processor TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by ltfschoen** [ImpulseDAO/Vara-Arena#58]
I encounter this issue when i follow the steps [shown here](https://github.com/ImpulseDAO/Vara-Arena/pull/56/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R74) even after adding following the [earlier steps](https://github.com/ImpulseDAO/Vara-Arena/pull/56/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R60) of using the Subsquid CLI to add the URL `wss://testnet-archive.vara.network` to the secrets.

To overcome this it has been necessary to hard-coding the URL in indexer/squid.yaml it as [mentioned here](https://github.com/ImpulseDAO/Vara-Arena/pull/56/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R85)

**Comment by tmcgroul** [comment]
secrets aren't supposed to work for local setup. it's just a way how to pass env variables to a squid deployed to subsquid cloud
