### ISSUE TITLE
lobby overview page [/arena] bug

### ISSUE THREAD

**Issue by 0xKube** [ImpulseDAO/Vara-Arena#62]
After creating a new lobby the /arena page doesn't show the newly created lobby. 

I guess it's somehow related to the limit for the number of lobbies on the /arena page.

It'd be great to fix the sorting issue as well. 

e.g. lobby 15 can't be higher than lobby 31 [as we sort by id by default] - 

@Rrock-k could you please investigate further?

![Image](https://github.com/ImpulseDAO/Vara-Arena/assets/47581603/9dff2559-2ba0-4140-b153-4952cc0e15c7)

Also I think we could introduce a feature that'd allow filtering lobbies based on Tiers.

**Comment by Rrock-k** [comment]
I sorted by ID and now everything works as expected. 

Not sure why the indexer sends lobbies in this order, maybe @tmcgroul knows

**Comment by tmcgroul** [comment]
postgres query engine doesn't guaranty ordered results if `ORDER BY` isn't specified. you could add ordering to a graphql query but it wouldn't work as expected because all id's in our db are strings (subsquid limitation).
client ordering is good enough for now 👍
